### ISSUE TITLE
Using tags are wrong 

### ISSUE THREAD

**Issue by rudnitskih** [MasterLuiji19/candies#11]
![image](https://user-images.githubusercontent.com/8848858/55688005-5649ba80-597c-11e9-96ec-55ee4a6ec3ba.png)

**Comment by MasterLuiji19** [comment]
I didn't understand the issues. Need to create a class for the all tag <a>?

**Comment by rudnitskih** [comment]
Yes, don't use tags and don't use nested classes, instead `.nav-list a` define and use something like `.topic-link` selector

**Comment by rudnitskih** [comment]
Not fixed

**Comment by MasterLuiji19** [comment]
why?

**Comment by rudnitskih** [comment]
ask me on the lesson I will explain again
